run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
    - revive
    - errcheck
    - gosimple
    - unused
  # structcheck and deadcode deprecated; using `unused` instead

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-issues-per-team: 0
