services:
  auth-service:
    container_name: auth-service
    build: .
    ports:
      - "${PORT}:9100"   
    restart: always
    environment:
      - APP_ENV=${APP_ENV}
      - PORT=${PORT}     
    networks:
      - app-network
    env_file:
      - .${APP_ENV}.env

networks:
  app-network:
    driver: bridge
